#!/usr/bin/env python

# nginx_fastcgi_cache_entries - Munin plugin to show number of files
# in the nginx fastcgi cache
#
# Author: Janek Noest
# License: http://opensource.org/licenses/bsd-license.php New BSD License

import sys
import commands

# Set this to the path you set for "fastcgi_cache_path" in your nginx.conf
folder = "/tmp/nginx/"

if len(sys.argv) == 2 and sys.argv[1] == "autoconf":
    print "yes"
elif len(sys.argv) == 2 and sys.argv[1] == "config":
    print "graph_title NGINX fastcgi cache entries";
    print "graph_args -l 0 --base 1000 --rigid";
    print "graph_category nginx";
    print "graph_vlabel Cache Entries";
    
    print "entries.label Entries";
    print "entries.draw STACK";
    print "entries.min 0";
else:
    entries = commands.getoutput('find ' + folder + ' -type f | wc -l')
    print "entries.value %i" % int(entries)
